name: Rails CI

on:
  push:
    branches: [ main ]
    paths:
      - 'code/rails/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'code/rails/**'

jobs:
  test-rails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Install SQLite3
        run: sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Bundle Install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        working-directory: code/rails

      - name: Run Tests
        run: bundle exec rails test
        working-directory: code/rails
